"""your message

Revision ID: 73b11eab50a0
Revises: 634e83f453b0
Create Date: 2025-02-05 20:00:49.989245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73b11eab50a0'
down_revision = '634e83f453b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'username')
    op.drop_column('messages', 'body')
    op.drop_column('messages', 'updated_at')
    op.drop_column('messages', 'created_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('created_at', sa.DATETIME(), nullable=True))
    op.add_column('messages', sa.Column('updated_at', sa.DATETIME(), nullable=True))
    op.add_column('messages', sa.Column('body', sa.VARCHAR(), nullable=True))
    op.add_column('messages', sa.Column('username', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
