"""your message

Revision ID: b946b98026ff
Revises: bf07ddf3e285
Create Date: 2025-02-05 20:13:50.207491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b946b98026ff'
down_revision = 'bf07ddf3e285'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
